dashboard_tickets_homepage:
    pattern:  /dashboard
    defaults: { _controller: DashboardTicketsBundle:Ticket:index }

dashboard_tickets_add:
    pattern:  /dashboard/ticket/add
    defaults: { _controller: DashboardTicketsBundle:Ticket:addTicket }

dashboard_tickets_adminitred:
    pattern:  /dashboard/ticket/administred
    defaults: { _controller: DashboardTicketsBundle:Ticket:administred }

dashboard_tickets_listNewsTickets:
    pattern:  /dashboard/ticket/attribute
    defaults: { _controller: DashboardTicketsBundle:Ticket:listNewsTickets }

dashboard_tickets_voir:
    pattern:  /dashboard/ticket/{id}
    defaults: { _controller: DashboardTicketsBundle:Ticket:voir }

dashboard_tickets_attribute:
    pattern:  /dashboard/ticket/attribute/{id}
    defaults: { _controller: DashboardTicketsBundle:Ticket:attribute }