parameters:
#    dashboard_tickets.example.class: Dashboard\TicketsBundle\Example

services:
#    dashboard_tickets.example:
#        class: %dashboard_tickets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
